In [12]:
import numpy as np

# 1. np.array()
# NumPy dizisi oluşturma
arr = np.array([1, 2, 3, 4, 5,6,7,8,9,10])
print("1. np.array():", arr)

1. np.array(): [ 1  2  3  4  5  6  7  8  9 10]


In [13]:
# 2. np.zeros()
# Belirtilen boyutta sıfırlarla dolu bir dizi oluşturma
zeros_arr = np.zeros((3, 15))
print("\n2. np.zeros():\n", zeros_arr)




2. np.zeros():
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [4]:
# 3. np.ones()
# Belirtilen boyutta birlerle dolu bir dizi oluşturma
ones_arr = np.ones((2, 4))
print("\n3. np.ones():\n", ones_arr)




3. np.ones():
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [5]:
# 4. np.arange()
# Belirtilen aralıktaki sayılarla dizi oluşturma
arange_arr = np.arange(0, 10, 2)
print("\n4. np.arange():", arange_arr)




4. np.arange(): [0 2 4 6 8]


In [6]:
# 5. np.linspace()
# Belirtilen aralıktaki sayıları eşit aralıklarla bölerek dizi oluşturma
linspace_arr = np.linspace(0, 1, 5)
print("\n5. np.linspace():", linspace_arr)




5. np.linspace(): [0.   0.25 0.5  0.75 1.  ]


In [7]:
# 6. np.random.rand()
# Belirtilen boyutta rastgele sayılar içeren dizi oluşturma
rand_arr = np.random.rand(3, 3)
print("\n6. np.random.rand():\n", rand_arr)




6. np.random.rand():
 [[0.71162052 0.38696269 0.47313527]
 [0.46684584 0.47496224 0.93674361]
 [0.22838803 0.55413833 0.85245314]]


In [8]:
# 7. np.random.randint()
# Belirtilen aralıkta rastgele tamsayılar içeren dizi oluşturma
randint_arr = np.random.randint(1, 10, (2, 3))
print("\n7. np.random.randint():\n", randint_arr)




7. np.random.randint():
 [[3 7 2]
 [9 8 6]]


In [9]:
# 8. np.reshape()
# Diziyi yeniden şekillendirme
reshaped_arr = np.arange(1, 10).reshape(3, 3)
print("\n8. np.reshape():\n", reshaped_arr)




8. np.reshape():
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
# 9. np.sum()
# Dizi elemanlarının toplamını hesaplama
sum_arr = np.sum(reshaped_arr)
print("\n9. np.sum():", sum_arr)




9. np.sum(): 45


In [11]:
# 10. np.mean()
# Dizi elemanlarının ortalamasını hesaplama
mean_arr = np.mean(reshaped_arr)
print("\n10. np.mean():", mean_arr)


10. np.mean(): 5.0
